# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#_pages contains index.md and about.md 
#because dumping all of your non-post page files into the root of the project directory is not ideal if you want to keep things organized
include: [_pages]


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JPTorrents's hub
#email: joelibus+githubpages@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "JPTorrents's hub centralizing my PhD on AI & experts collaboration in healthcare, scientific articles, substack blog, other ressources, pojects and CV."
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jptorrents.github.io"
#twitter_username: jekyllrb
github_username:  JPTorrents

# Build settings
markdown: kramdown
theme: null # minima
plugins:
  - jekyll-feed

# Front Matter Defaults
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /posts/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
