title: Joel Perez-Torrents
email: jpereztorrents+github@gmail.com
description: >-
  Personal academic website of Joel Perez-Torrents. Research themes,
  publications, and academic profile.
baseurl: ""
url: "https://jptorrents.github.io"
github_username: JPTorrents
lang: en

author:
  name: Joel Perez-Torrents
  given_name: Joel
  family_name: Perez-Torrents
  job_title: Postdoctoral Researcher / Fellow
  affiliation: Desautels, McGill University / CRG, Ecole polytechnique
  email: jpereztorrents+github@gmail.com
  same_as:
    - https://orcid.org/0009-0008-5860-1948
    - https://scholar.google.com/citations?user=a-3uzfgAAAAJ&hl=en
    - https://github.com/JPTorrents
    - https://jptorrents.substack.com

markdown: kramdown
theme: null
plugins:
  - jekyll-feed

sass:
  style: compressed
  sass_dir: _sass

# Ensure custom pages collection-like directory is processed by GitHub Pages/Jekyll
include:
  - _pages

collections:
  publications:
    output: true
    permalink: /publications/:name/

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:categories/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
  -
    scope:
      type: publications
      path: _publications
    values:
      layout: publication
